apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrdemo-sp-deployment
  labels:
    app: acrdemo-sp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrdemo-sp
  template:
    metadata:
      labels:
        app: acrdemo-sp
    spec:
      containers:
        - name: acrdemo-sp-container 
          image: acrsprepository.azurecr.io/app2/acr-app2:v1   # Update Image Name 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:   # using this secret it is going to pull the image from ACR
        - name: acr-secret  
        


   